--Table created as: create table task_entity (id bigint generated by default as identity, creation_date date not null, description varchar(1024), due_date date not null, status varchar(10), title varchar(255), primary key (id))

-- The order in which the entity table columns are inserted are : id, creation_date, description, due_date, status, title
 
INSERT INTO task_entity VALUES (1, '2019-04-11', 'test descr', '2019-04-12', 'P1', 'Supermarket'),(2, '2019-04-13', 'Yogurt', '2019-04-14', 'P2', 'Supermarket'),(3, '2019-04-13', 'Vegetables', '2020-03-15', 'P3', 'Supermarket'),(4, '2020-04-13', 'Icecream', '2020-04-14', 'P4', 'Supermarket');

ALTER TABLE task_entity ALTER COLUMN id RESTART WITH 5;